### ISSUE TITLE
Line 1438 : Illegal function call (LOCATE errors at smaller screen sizes)

### ISSUE THREAD

**Issue by AshishKingdom** [Targon-Industries/DATANET#1]
![Screenshot_0](https://user-images.githubusercontent.com/21278020/87144319-3282cc00-c2c5-11ea-86a2-872322070bf2.png)

**Comment by loudar** [comment]
Hey Ashish! Thanks for submitting this issue.
Try opening \data\settings.datnet with an editor and increasing the third value (somehwere from 1.0 to 2.5). The line that causes the Illegal function call is a LOCATE statement, so it is likely out of bounds.
How big is the screen you're starting DATANET on?

**Comment by AshishKingdom** [comment]
@loudar I have 1366 x 768

**Comment by loudar** [comment]
> @loudar I have 1366 x 768

That should technically work I think. Have you tried changing the value?

**Comment by loudar** [comment]
Fixed the issue by implementing set screen sizes for screens bigger than 1500, below that it's just the desktop width. Will have to check that all placement will be done inside the window.
